const text = `ooooooooo++ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooo+++//++//++++ooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooo+++::-:-::----://+++++++oooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooo/--.---.---.--...-.:::://:/+oooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooo+:---..........'....--.-:/:-::+///+/+ooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooo++/-..........''''....--..-----://////:+o+++oooooooooooooooooooooooooooooo
ooooooooooooooooooooooooo/----.'.....-.'.'..-.:.--..--:--:::++//:/+/oooooooooooooooooooooooooooooooo
oooooooooooooooooooooooo+/-.''''''....''..:/-:/.-:--:-:/-:::+o+:-+:o+ooooooooooooooooooooooooooooooo
ooooooooooooooooooooooo+-.''''''''''''''.-//--::-:--::/::+--/++/:::ooo+ooooooooooooooooooooooooooooo
oooooooooooooooosoooooo-..'''''''''''''...:::::---:---:--/:-////:-:oo/++oooooooooooooooosooooooooooo
ssssssssssssssssssssss+:-.'.''''.........--------------:://///////+++++/+oosssssssssssssssssssssssss
sssssssssssssssssssss+//-..'''''......-----.-------::://+/+++++++///++++osssssssssssssssssssssssssss
sssssssssssssssssssso-.'''..'''...----.......-----::////++oossoo+/+++ooossssssssssssssssssssssssssss
sssssssssssssssssssss:.''''''''.--............-----::///++ossssso+/++++ssossssssssssssssssssssssssss
sssssssssssssssssssso:-''''''''.-.................--::://+ossssss+++oosssossssssssssssssssssssssssss
ssssssssssssssssssssso:.'''''''...................---:://++oossysooossssssssssssssssssssssssssssssss
ssssssssssssssssssssso/-.'''''.-.................---:::////+ossysooosyysysssssssssssssssssssssssssss
ssssssssssssssssssssss+-..'''..-.................----::////+osyysosssyyyyyssssssssssssssssssssssssss
yyyyyyyyyyyyyyysssyyyys/.'''...-..................--:::///++osyyysssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyysyyyyyo-'''.-----::----..........-:://++++ossyyyyyyyyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyyo-.'...-:/+++ooso+/:-..-.-://+osyyyyhhhyyyyyhyyhhhyyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyys-.'--.-::....-::---....-:/++/::::/+shddyyyyhyshhyyyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyys-..--....:/ossdy+:-..'.:oss+//++ysoooyhyyyyyyshhhdyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyys-.--.........----.....-/oso/:--://+osoossyyyyshdhsyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyyy:.--........-.....----:++oso/::---:/++oosyyyhhdhsoyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyyy/.---....-------..----/+o+++/:::::::/+oosyhhdmhyysyyyyyyyyyyyyyyyyyyyyyyyyyy
yyyyyyyyyyyyyyyyyyyyyyyy/----..........------:+osso+:---:::/+osssyhddho+yyyyyyyyyyyyyyyyyyyyyyyyyyyy
hhhhhhhhhhhhhhhhhhhhhhhh/----...'''.-:/:---..-/osssss/-..-:/+ossyhhdddssyhhhhhhhhhhhhhhhhhhhhhhhhhhy
hhhhhhhhhhhhhhhhhhhhhhhh/---....''.-/+:.----.-/oyyyys+:..--:+osyyhhhddsyyhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhs:---.....-/o+:://+++++yyyyysso:---:/osyyhhhdmyyhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhss---....-/os+/++++os++osyyhyyys:--/+ossyhhhdmyhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhys:--....-+osss+/::////+osssyyhyo--/+ossyyhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhho:-.....-+so/+--:-.:-:/osyhsoso.-/+ooosyhddmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhh/-......+o:..--::-::/+ooso//s:.:oo++oshdddNmhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhy:-....-so-...-..---::/oo+//o/:+o//+syhhdmNNmhhhhhhhhhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhhhhhhhhhhhy/-...:s+-...-:://///+++//oyyo+/:/oyhhhdNNNNmhhhhhhhhhhhhhhhhhhhhhhhhhhh
dddddddddddddddddddddddddddddy:-../yo:..--/:/++++++++oyhdo+//oyhyymNNNNNNddddddddddddddddddddddddddd
dddddddddddddddddddddddddddddmh:-./yyo---:::://+oooooydmmoo+osyyhmNNNNNNNNdddddddddddddddddddddddddd
dddddddddddddddddddddddddddmmNM///oyhy+:-:/://:/+oosydmNdsoosyydmNNNNNNNNNNddddddddddddddddddddddddd
ddddddddddddddddddddddddddmmNNM/+syhhdhys+++++++sydmmNNmhsssyhdmNNNNNNNNNNNNNmdddddddddddddddddddddd
ddddddddddddddddddddddddhmmNNNNo/+ssyhdddys++++ohdNNNNNmdyyyhdmmNNNNNNNNNNNNNNNNmmdddddddddddddddddd
dddddddddddddddddddddddmmdmNNNNs+/:///+oooo+++oyhmmdmmmmmdddmmmNNNNNNNNNNNNNmNNNmNmmmmdddddddddddddd
ddddddddddddddddddddhhNMMNdddmmyo+//:::::://ossssssssyddmNNMMNNmNNNNNNNNNNNmmmNmmmmmdddmmmmddddddddd
dddddddddddddddddddddmNNmdNmdNdhso++//::--:/+oo++/+sdmNNNNNNNNNMNNmNNNNNNNNmmmNmmmmmddddddmmmmmmdddd
dddddddddddddddhdddddNmdddmmdddhhyso+//:----:/::-:hmmNNNNNNNNmNNMNNNmNNNNmmmmNNmmmmdddddddddddmmmmmm
dddddddddddddddhyhddddhdddhdhyyyyyysso+/:--..-...sNNNNmNNNmmmmNNmmmmmmmmmmmmmmmmddddddddddddddddmmmm
ddddddddddddhhddhhddddhhddhddyyyyyyssoo+/:--...../NNNNmNmmmmmNNmmmdddddmddddmmmddhddhhhddddddddddmmm
dddddhhhhhddhhhhhhdddhhhddhddhyyyyyyooo+/:--.....+NNNNmdmmmNmmmdddddddddddhdddddddddhhhhdhddddddddmm
`;

console.log(text);
